server:
  port: 9001
spring:
  application:
    name: ihrm-company
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true